version: '3.7'
services:
  redis:
    image: redis
    networks:
      - webnet
  db:
    image: postgres
    environment:
      DATABASE: slack_clone
      POSTGRES_DB: slack_clone
      DATABASE_PASSWORD: postgres
      DATABASE_USER: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - webnet
    ports:
      - '3030:5432'
  web:
    image: javenkn/slack-clone-server:latest
    depends_on:
      - db
      - redis
    networks:
      - webnet
    volumes:
      - ./files:/files
    environment:
      DATABASE: slack_clone
      DATABASE_USER: postgres
      DB_HOST: db
      REDIS_HOST: redis
      SECRET: ${SECRET}
    command: ['./wait-for-it.sh', 'db:5432', '--', 'node', 'index.js']
  nginx:
    image: nginx
    volumes:
      - ./mysite.template:/etc/nginx/conf.d/mysite.template
      - ./files:/files
    ports:
      - 3000:80
    networks:
      - webnet
    depends_on:
      - web
    command: /bin/bash -c "cat /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
networks:
  webnet:
